### ISSUE TITLE
No need in i-bem block, if we want only elems

### ISSUE THREAD

**Issue by YetiOr** [eGavr/bemhint#6]
if our block depends on ``i-bem__i18n``
we expect ``{ block: 'i-bem', elem: 'i18n'  }``
not ``{ block: 'i-bem', elems: ['i18n']  }``

**Comment by eGavr** [comment]
The main idea during the comparison of actual and expected deps is to transform them to the comparable form, this way the expected deps in the diff may be shown in a _long_ form.

It seems that the variant `{ block: 'i-bem', elems: ['i18n'] }` is valid too and there will be no diff if the actual deps will be `{ block: 'i-bem', elem: 'i18n' }`.
