### ISSUE TITLE
Wrong actual deps

### ISSUE THREAD

**Issue by YetiOr** [eGavr/bemhint#7]
my block has such deps:
``
{block: 'i-bem', elem: 'html'},
``
but bemhint shows actual deps as
``
actual:   { block: 'i-bem', elems: [ 'html' ] }
``
so this is a huge difference: https://en.bem.info/tools/bem/bem-tools/depsjs/#include-several-elements

**Comment by eGavr** [comment]
`bemhint` tries to _normalize_ the actual deps and transforms them to comparable form with expected deps, I mean, that if your deps file is the following:

```
{block: 'i-bem', elem: 'html'}
```

and the expected deps are

```
{ block: 'i-bem', elems: [ 'html' ] }
```

there will be no diffs.

**Comment by YetiOr** [comment]
you can normalize them for comparison
but show actual deps while logging?

**Comment by eGavr** [comment]
Yes, I think that actual deps should be shown AS IS in the log of diffs.
