### ISSUE TITLE
Rewrite of block: i-bem elem: deps

### ISSUE THREAD

**Issue by YetiOr** [eGavr/bemhint#8]
if my block has deps like this: 
```
    mustDeps: [
        {block: 'i-bem', elem: 'i18n'},
        {block: 'i-bem', elem: 'html'},

```

then bemhint will read actual deps only of last statement:
```
actual:   { block: 'i-bem', elems: [ 'html' ] }
```

**Comment by eGavr** [comment]
Why do not you write this ->

```
    mustDeps: [
        {block: 'i-bem', elems: ['i18n', 'html']}
    ]
```
?

I think that the first variant is not really a good _bem style_

**Comment by YetiOr** [comment]
I think you right for `i-bem` block
but think about `i-ua`
deps can be:
```
block: 'i-ua', elem: 'svg'
block: 'i-ua', elem: 'retina'
```
and in his case we don't need block itself

**Comment by eGavr** [comment]
_bemhint_ checks _i-bem_ deps now, so it seems that we can use everything AS IS.
